export default {
  "javascript": ["js", "javascript", "ecmascript"],
  "typescript": ["ts", "typescript"],
  "html5": ["html", "html5"],
  "css3": ["css", "css3"],
  "sass": ["scss", "sass"],
  "reactjs": ["react", "reactjs", "react.js"],
  "nextjs": ["next", "nextjs", "next.js"],
  "nodejs": ["node", "nodejs", "node.js"],
  "mongodb": ["mongo", "mongodb", "nosql"],
  "git": ["git", "gitlab", "github", "version control"],
  "tailwindcss": ["tailwind", "tailwindcss"],
  "material-ui": ["mui", "material-ui"],
  "responsive design": ["responsive web design", "mobile-first design"],
  "php": ["php programming", "php"],
  "sql": ["sql queries", "sql", "database queries"],
  "mysql": ["mysql", "sql database"],
  "software testing": ["testing", "qa", "quality assurance"],
  "selenium": ["selenium", "automation testing"],
  "frontend development": ["frontend", "front-end", "ui development"],
  "backend development": ["backend", "back-end", "server-side development"],
  "database management": ["db management", "database administration"],

  "accounting": ["accounting", "general ledger management", "accounts payable", "accounts receivable", "bookkeeping"],
  "financial reporting": ["financial statements", "financial reporting", "accounting reports"],
  "tax preparation": ["tax filing", "tax preparation", "taxation", "tax compliance"],
  "auditing": ["audit", "auditing", "financial audit"],
  "general ledger management": ["general ledger", "ledger management", "gl management"],
  "accounts payable": ["ap", "accounts payable"],
  "accounts receivable": ["ar", "accounts receivable"],
  "excel": ["excel", "microsoft excel", "office software", "spreadsheets"],
  "quickbooks": ["quickbooks", "qb", "accounting software"],
  "sap": ["sap", "erp", "sap erp"],

  "communication": ["interpersonal skills", "communication skills", "communication"],
  "teamwork": ["collaboration", "team work", "teamwork"],
  "problem-solving": ["problem solving", "critical thinking"],
  "self-study": ["self-learning", "independent learning"],
  "analytical thinking": ["analytical thinking", "data analysis", "analytics"],
  "compliance knowledge": ["regulatory compliance", "compliance", "legal compliance"],

  "seo": ["search engine optimization", "seo", "on-page seo"],
  "paid advertising": ["ppc", "paid ads", "online advertising"],
  "google analytics": ["ga4", "google analytics", "web analytics"],
  "cms": ["content management system", "wordpress", "cms"],
  "digital marketing": ["online marketing", "digital marketing", "internet marketing"],

  "photoshop": ["adobe photoshop", "photoshop", "photo editing"],
  "illustrator": ["adobe illustrator", "illustrator", "vector design"],
  "figma": ["figma", "ui design", "prototyping"],
  "ui/ux design": ["ui design", "ux design", "user interface", "user experience"],

  "aws": ["amazon web services", "aws", "cloud aws"],
  "docker": ["docker", "containerization"],
  "kubernetes": ["k8s", "kubernetes", "container orchestration"],
  "jenkins": ["jenkins", "ci/cd", "continuous integration"],
  "terraform": ["terraform", "infrastructure as code", "iac"],
  "ci/cd": ["continuous integration", "continuous deployment", "ci/cd"],

  "python": ["python", "python programming"],
  "tensorflow": ["tensorflow", "tf", "machine learning"],
  "pytorch": ["pytorch", "deep learning"],
  "scikit-learn": ["scikit-learn", "sklearn", "machine learning"],
  "nlp": ["natural language processing", "nlp"],
  "deep learning": ["deep learning", "neural networks"],

  "hr management": ["human resources", "hr", "hr management"],
  "recruitment": ["hiring", "recruitment", "talent acquisition"],
  "office administration": ["office management", "administration", "admin"],

  "sales": ["sales", "selling", "business development"],
  "negotiation": ["negotiation", "deal closing"],
  "customer service": ["customer support", "client service", "customer service"],
  "it solutions": ["it sales", "technology solutions", "it solutions"],

  "active directory": ["active directory", "ad", "windows ad"],
  "office 365": ["office 365", "microsoft 365", "m365"],
  "ticketing system": ["ticketing", "helpdesk system"],
  "windows os": ["windows", "windows os", "windows operating system"],
  "linux": ["linux", "unix"],
  "networking": ["network administration", "networking", "network support"],

  "cloud computing": ["cloud", "cloud computing", "aws", "azure"],
};